api:
  image: gregdaynes/example-bramble-api:master
  links:
    - db
    - cache
  ports:
    - "3000:3000"
  environment:
    - "DEBUG=*,-express:*"
    - DEBUG_COLORS=true
    - NODE_ENV=development
    - PORT=3000
  command: npm start

db:
  extends:
    file: ../example-compose/common-services.yml
    service: db

cache:
  extends:
    file: ../example-compose/common-services.yml
    service: cache
