api:
  image: docker pull gregdaynes/example-bramble-api
  links:
    - db
    - cache
  environment:
    - "DEBUG=*,-express:*"
    - DEBUG_COLORS=true
    - NODE_ENV=development
    - PORT=3000
  command: npm start

db:
  extends:
    file: ../example-compose/common-services.yml
    service: db

cache:
  extends:
    file: ../example-compose/common-services.yml
    service: cache
